// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
#import <Foundation/Foundation.h>
#import <Capacitor/Capacitor.h>

// Define the plugin using the CAP_PLUGIN Macro, and
// each method the plugin supports using the CAP_PLUGIN_METHOD macro.
CAP_PLUGIN(AdMobPlusPlugin, "AdMobPlus",
           CAP_PLUGIN_METHOD(start, CAPPluginReturnPromise);
           CAP_PLUGIN_METHOD(configure, CAPPluginReturnPromise);
           CAP_PLUGIN_METHOD(configRequest, CAPPluginReturnPromise);
           CAP_PLUGIN_METHOD(adCreate, CAPPluginReturnPromise);
           CAP_PLUGIN_METHOD(adIsLoaded, CAPPluginReturnPromise);
           CAP_PLUGIN_METHOD(adLoad, CAPPluginReturnPromise);
           CAP_PLUGIN_METHOD(adShow, CAPPluginReturnPromise);
           CAP_PLUGIN_METHOD(adHide, CAPPluginReturnPromise);
           CAP_PLUGIN_METHOD(trackingAuthorizationStatus, CAPPluginReturnPromise);
           CAP_PLUGIN_METHOD(requestTrackingAuthorization, CAPPluginReturnPromise);
)
