// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
package admob.suite;

final class Actions {
    static final String READY = "ready";
    static final String BANNER_SHOW = "banner_show";
    static final String INTERSTITIAL_PREPARE = "interstitial_prepare";
    static final String INTERSTITIAL_SHOW = "interstitial_show";
}
