// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
package admob.suite;

final class Events {
    static final String READY = "admob.ready";
    static final String INTERSTITIAL_LOAD = "admob.interstitial.load";
    static final String INTERSTITIAL_LOAD_FAIL = "admob.interstitial.load_fail";
    static final String INTERSTITIAL_OPEN = "admob.interstitial.open";
    static final String INTERSTITIAL_CLOSE = "admob.interstitial.close";
    static final String INTERSTITIAL_EXIT_APP = "admob.interstitial.exit_app";
}
