// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
'use strict'

const AdMob = {
  bannerConfig() {},
  bannerHide() {},
  bannerLoad() {},
  bannerShow() {},
  configRequest() {},
  interstitialIsLoaded() {},
  interstitialLoad() {},
  interstitialShow() {},
  ready() {},
  requestTrackingAuthorization() {},
  rewardedInterstitialIsLoaded() {},
  rewardedInterstitialLoad() {},
  rewardedInterstitialShow() {},
  rewardedIsLoaded() {},
  rewardedLoad() {},
  rewardedShow() {},
  setAppMuted() {},
  setAppVolume() {},
  start() {},
}

// eslint-disable-next-line node/no-missing-require
require('cordova/exec/proxy').add('AdMob', AdMob)
