// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
'use strict';

const AdMob = {
  adCreate() {},
  adHide() {},
  adIsLoaded() {},
  adLoad() {},
  adShow() {},
  bannerConfig() {},
  configure() {},
  ready() {},
  start() {},
  webviewGoto() {},
};

// eslint-disable-next-line
require('cordova/exec/proxy').add('AdMob', AdMob);
