// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
package admob.plus.capacitor;

public final class Generated {
    public final class Events {
        public static final String BANNER_CLICK = "banner.click";
        public static final String BANNER_CLOSE = "banner.close";
        public static final String BANNER_IMPRESSION = "banner.impression";
        public static final String BANNER_LOAD = "banner.load";
        public static final String BANNER_LOAD_FAIL = "banner.loadFail";
        public static final String BANNER_OPEN = "banner.open";
        public static final String INTERSTITIAL_DISMISS = "interstitial.dismiss";
        public static final String INTERSTITIAL_LOAD = "interstitial.load";
        public static final String INTERSTITIAL_LOAD_FAIL = "interstitial.loadFail";
        public static final String INTERSTITIAL_SHOW = "interstitial.show";
        public static final String INTERSTITIAL_SHOW_FAIL = "interstitial.showFail";
        public static final String REWARDED_DISMISS = "rewarded.dismiss";
        public static final String REWARDED_INTERSTITIAL_DISMISS = "rewardedInterstitial.dismiss";
        public static final String REWARDED_INTERSTITIAL_LOAD = "rewardedInterstitial.load";
        public static final String REWARDED_INTERSTITIAL_LOAD_FAIL = "rewardedInterstitial.loadFail";
        public static final String REWARDED_INTERSTITIAL_REWARD = "rewardedInterstitial.reward";
        public static final String REWARDED_INTERSTITIAL_SHOW = "rewardedInterstitial.show";
        public static final String REWARDED_INTERSTITIAL_SHOW_FAIL = "rewardedInterstitial.showFail";
        public static final String REWARDED_LOAD = "rewarded.load";
        public static final String REWARDED_LOAD_FAIL = "rewarded.loadFail";
        public static final String REWARDED_REWARD = "rewarded.reward";
        public static final String REWARDED_SHOW = "rewarded.show";
        public static final String REWARDED_SHOW_FAIL = "rewarded.showFail";
    }
}
