import fs from 'fs'
import path from 'path'

const warnMessage =
  'THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.'

enum Actions {
  ready = 'ready',
  banner_show = 'banner_show',
  interstitial_prepare = 'interstitial_prepare',
  interstitial_show = 'interstitial_show',
}

enum Events {
  ready = 'admob.ready',
  interstitial_load = 'admob.interstitial.load',
  interstitial_load_fail = 'admob.interstitial.load_fail',
  interstitial_open = 'admob.interstitial.open',
  interstitial_close = 'admob.interstitial.close',
  interstitial_exit_app = 'admob.interstitial.exit_app',
}

function buildActionsJava(): string {
  const linesActions = []
  for (const k in Actions) {
    linesActions.push(
      `    static final String ${k.toUpperCase()} = "${Actions[k]}";`,
    )
  }
  return `// ${warnMessage}
package admob.suite;

final class Actions {
${linesActions.join('\n')}
}
`
}

function buildConstantsTs(): string {
  const linesActions = []
  for (const k in Actions) {
    linesActions.push(`  ${k} = '${Actions[k]}',`)
  }

  const linesEvents = []
  for (const k in Events) {
    linesEvents.push(`  ${k} = '${Events[k]}',`)
  }
  return `// ${warnMessage}
export const enum NativeActions {
  Service = 'AdMob',
${linesActions.join('\n')}
}

export const enum Events {
${linesEvents.join('\n')}
}
`
}

function main() {
  const l = [
    { filepath: 'src/android/Actions.java', f: buildActionsJava },
    { filepath: 'ts/constants.ts', f: buildConstantsTs },
  ]
  return Promise.all(
    l.map(({ filepath, f }) =>
      fs.promises.writeFile(path.join(__dirname, '..', filepath), f(), 'utf8'),
    ),
  )
}

main()
