import fs from 'fs'
import path from 'path'

import glob from 'fast-glob'
import replace from 'replace-in-file'

const warnMessage =
  'THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.'

/* tslint:disable:object-literal-sort-keys */
const Actions: { [index: string]: string } = {
  ready: 'ready',

  banner_show: 'banner_show',

  interstitial_prepare: 'interstitial_prepare',
  interstitial_show: 'interstitial_show',
}

const Events: { [index: string]: string } = {
  ready: 'admob.ready',

  interstitial_load: 'admob.interstitial.load',
  interstitial_load_fail: 'admob.interstitial.load_fail',
  interstitial_open: 'admob.interstitial.open',
  interstitial_close: 'admob.interstitial.close',
  interstitial_exit_app: 'admob.interstitial.exit_app',
}
/* tslint:enable:object-literal-sort-keys */

function buildActionsJava(): string {
  const linesActions = Object.keys(Actions)
    .map(k => `    static final String ${k.toUpperCase()} = "${Actions[k]}";`)
    .join('\n')

  return `// ${warnMessage}
package admob.suite;

final class Actions {
${linesActions}
}
`
}

function buildEventsJava(): string {
  const linesEvents = Object.keys(Events)
    .map(k => `    static final String ${k.toUpperCase()} = "${Events[k]}";`)
    .join('\n')

  return `// ${warnMessage}
package admob.suite;

final class Events {
${linesEvents}
}
`
}

function buildConstantsTs(): string {
  const linesActions = Object.keys(Actions)
    .map(k => `  ${k} = '${Actions[k]}',`)
    .join('\n')

  const linesEvents = Object.keys(Events)
    .map(k => `  ${k} = '${Events[k]}',`)
    .join('\n')

  return `// ${warnMessage}
export const enum NativeActions {
  Service = 'AdMob',
${linesActions}
}

export const enum Events {
${linesEvents}
}
`
}

async function updateConfigXML() {
  const [androidFiles, iosFiles] = await Promise.all([
    glob(['**/*.java'], { cwd: path.join(__dirname, '../src/android') }),
    glob(['*.swift'], { cwd: path.join(__dirname, '../src/ios') }),
  ])
  const androidContent = androidFiles
    .map(s => {
      let d = path.dirname(s.toString())
      if (d === '.') {
        d = ''
      } else {
        d = `/${d}`
      }
      return `        <source-file src="src/android/${s}" target-dir="src/admob/suite${d}" />`
    })
    .join('\n')
  const iosContent = iosFiles
    .map(s => `        <source-file src="src/ios/${s}" />`)
    .join('\n')
  await replace({
    files: [path.join(__dirname, '../plugin.xml')],
    from: /([\s\S]*ANDROID_BEGIN -->\n)[\s\S]*(\n\s+<!-- AUTOGENERATED: ANDROID_END[\s\S]*IOS_BEGIN -->\n)[\s\S]*(\n\s+<!-- AUTOGENERATED: IOS_END[\s\S]*)/,
    to: `$1${androidContent}$2${iosContent}$3`,
  })
}

async function main() {
  const l = [
    { filepath: 'src/android/Actions.java', f: buildActionsJava },
    { filepath: 'src/android/Events.java', f: buildEventsJava },
    { filepath: 'ts/constants.ts', f: buildConstantsTs },
  ]
  await Promise.all(
    l.map(({ filepath, f }) =>
      fs.promises.writeFile(path.join(__dirname, '..', filepath), f(), 'utf8'),
    ),
  )

  await updateConfigXML()
}

main()
