// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
package cordova.plugin.consent

object Actions {
    const val CAN_REQUEST_ADS = "canRequestAds"
    const val GET_CONSENT_STATUS = "getConsentStatus"
    const val GET_FORM_STATUS = "getFormStatus"
    const val LOAD_AND_SHOW_IF_REQUIRED = "loadAndShowIfRequired"
    const val LOAD_FORM = "loadForm"
    const val PRIVACY_OPTIONS_REQUIREMENT_STATUS = "privacyOptionsRequirementStatus"
    const val READY = "ready"
    const val REQUEST_INFO_UPDATE = "requestInfoUpdate"
    const val REQUEST_TRACKING_AUTHORIZATION = "requestTrackingAuthorization"
    const val RESET = "reset"
    const val SHOW_FORM = "showForm"
    const val SHOW_PRIVACY_OPTIONS_FORM = "showPrivacyOptionsForm"
    const val TRACKING_AUTHORIZATION_STATUS = "trackingAuthorizationStatus"
}

object Events {
    const val READY = "consent.ready"
}

object ConsentStatus {
    const val UNKNOWN = 0
    const val REQUIRED = 1
    const val NOT_REQUIRED = 2
    const val OBTAINED = 3
}
