// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
package cordova.plugin.consent;

public final class Generated {
    public final class Actions {
        public static final String GET_CONSENT_STATUS = "getConsentStatus";
        public static final String GET_FORM_STATUS = "getFormStatus";
        public static final String LOAD_FORM = "loadForm";
        public static final String READY = "ready";
        public static final String REQUEST_INFO_UPDATE = "requestInfoUpdate";
        public static final String RESET = "reset";
        public static final String SHOW_FORM = "showForm";
    }

    public final class Events {
        public static final String READY = "consent.ready";
    }
}
