// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
package cordova.plugin.consent

class Generated {
    object Actions {
        const val GET_CONSENT_STATUS = "getConsentStatus"
        const val GET_FORM_STATUS = "getFormStatus"
        const val LOAD_FORM = "loadForm"
        const val READY = "ready"
        const val REQUEST_INFO_UPDATE = "requestInfoUpdate"
        const val REQUEST_TRACKING_AUTHORIZATION = "requestTrackingAuthorization"
        const val RESET = "reset"
        const val SHOW_FORM = "showForm"
        const val TRACKING_AUTHORIZATION_STATUS = "trackingAuthorizationStatus"
    }

    object Events {
        const val READY = "consent.ready"
    }

    object ConsentStatus {
        const val UNKNOWN = 0
        const val REQUIRED = 1
        const val NOT_REQUIRED = 2
        const val OBTAINED = 3
    }
}
