// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
export const enum NativeActions {
  Service = 'AdMob',
  banner_hide = 'banner_hide',
  banner_show = 'banner_show',
  interstitial_load = 'interstitial_load',
  interstitial_show = 'interstitial_show',
  ready = 'ready',
  reward_video_load = 'reward_video_load',
  reward_video_show = 'reward_video_show',
  set_app_muted = 'set_app_muted',
  set_app_volume = 'set_app_volume',
}

export const enum Events {
  banner_close = 'admob.banner.close',
  banner_exit_app = 'admob.banner.exit_app',
  banner_load = 'admob.banner.load',
  banner_load_fail = 'admob.banner.load_fail',
  banner_open = 'admob.banner.open',
  interstitial_close = 'admob.interstitial.close',
  interstitial_exit_app = 'admob.interstitial.exit_app',
  interstitial_load = 'admob.interstitial.load',
  interstitial_load_fail = 'admob.interstitial.load_fail',
  interstitial_open = 'admob.interstitial.open',
  ready = 'admob.ready',
  reward_video_close = 'admob.reward_video.close',
  reward_video_complete = 'admob.reward_video.complete',
  reward_video_exit_app = 'admob.reward_video.exit_app',
  reward_video_load = 'admob.reward_video.load',
  reward_video_load_fail = 'admob.reward_video.load_fail',
  reward_video_open = 'admob.reward_video.open',
  reward_video_reward = 'admob.reward_video.reward',
  reward_video_start = 'admob.reward_video.start',
}

export const enum TestIds {
  banner_android = 'ca-app-pub-3940256099942544/6300978111',
  interstitial_android = 'ca-app-pub-3940256099942544/1033173712',
  reward_video_android = 'ca-app-pub-3940256099942544/5224354917',
  banner_ios = 'ca-app-pub-3940256099942544/2934735716',
  interstitial_ios = 'ca-app-pub-3940256099942544/4411468910',
  reward_video_ios = 'ca-app-pub-3940256099942544/1712485313',
}
