// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
export enum NativeActions {
  Service = 'AdMob',
  bannerHide = 'banner.hide',
  bannerShow = 'banner.show',
  configRequest = 'configRequest',
  interstitialIsLoaded = 'interstitial.isLoaded',
  interstitialLoad = 'interstitial.load',
  interstitialShow = 'interstitial.show',
  ready = 'ready',
  rewardedIsReady = 'rewarded.isReady',
  rewardedLoad = 'rewarded.load',
  rewardedShow = 'rewarded.show',
  setAppMuted = 'setAppMuted',
  setAppVolume = 'setAppVolume',
}

export enum Events {
  bannerClick = 'admob.banner.click',
  bannerClose = 'admob.banner.close',
  bannerImpression = 'admob.banner.impression',
  bannerLoad = 'admob.banner.load',
  bannerLoadFail = 'admob.banner.loadFail',
  bannerOpen = 'admob.banner.open',
  initComplete = 'admob.initComplete',
  interstitialClick = 'admob.interstitial.click',
  interstitialClose = 'admob.interstitial.close',
  interstitialImpression = 'admob.interstitial.impression',
  interstitialLoad = 'admob.interstitial.load',
  interstitialLoadFail = 'admob.interstitial.loadFail',
  interstitialOpen = 'admob.interstitial.open',
  ready = 'admob.ready',
  rewardedClose = 'admob.rewarded.close',
  rewardedLoad = 'admob.rewarded.load',
  rewardedLoadFail = 'admob.rewarded.loadFail',
  rewardedOpen = 'admob.rewarded.open',
  rewardedReward = 'admob.rewarded.reward',
  rewardedShowFail = 'admob.rewarded.showFail',
}

export enum AdSizeType {
  BANNER,
  LARGE_BANNER,
  MEDIUM_RECTANGLE,
  FULL_BANNER,
  LEADERBOARD,
  SMART_BANNER,
}
