// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { WebPlugin } from '@capacitor/core'
import type { AdMobPlusPlugin } from './definitions'

export class AdMobPlusWeb extends WebPlugin implements AdMobPlusPlugin {
  async start(
    ...opts: Parameters<AdMobPlusPlugin['start']>
  ): ReturnType<AdMobPlusPlugin['start']> {
    console.log('start', opts)
  }

  async configure(
    ...opts: Parameters<AdMobPlusPlugin['configure']>
  ): ReturnType<AdMobPlusPlugin['configure']> {
    console.log('configure', opts)
  }

  async configRequest(
    ...opts: Parameters<AdMobPlusPlugin['configRequest']>
  ): ReturnType<AdMobPlusPlugin['configRequest']> {
    console.log('configRequest', opts)
  }

  async adCreate(
    ...opts: Parameters<AdMobPlusPlugin['adCreate']>
  ): ReturnType<AdMobPlusPlugin['adCreate']> {
    console.log('adCreate', opts)
  }

  async adIsLoaded(
    ...opts: Parameters<AdMobPlusPlugin['adIsLoaded']>
  ): ReturnType<AdMobPlusPlugin['adIsLoaded']> {
    console.log('adIsLoaded', opts)
    return false
  }

  async adLoad(
    ...opts: Parameters<AdMobPlusPlugin['adLoad']>
  ): ReturnType<AdMobPlusPlugin['adLoad']> {
    console.log('adLoad', opts)
  }

  async adShow(
    ...opts: Parameters<AdMobPlusPlugin['adShow']>
  ): ReturnType<AdMobPlusPlugin['adShow']> {
    console.log('adShow', opts)
  }

  async adHide(
    ...opts: Parameters<AdMobPlusPlugin['adHide']>
  ): ReturnType<AdMobPlusPlugin['adHide']> {
    console.log('adHide', opts)
  }

  async trackingAuthorizationStatus(
    ...opts: Parameters<AdMobPlusPlugin['trackingAuthorizationStatus']>
  ): ReturnType<AdMobPlusPlugin['trackingAuthorizationStatus']> {
    console.log('trackingAuthorizationStatus', opts)
    return { status: false }
  }

  async requestTrackingAuthorization(
    ...opts: Parameters<AdMobPlusPlugin['requestTrackingAuthorization']>
  ): ReturnType<AdMobPlusPlugin['requestTrackingAuthorization']> {
    console.log('requestTrackingAuthorization', opts)
    return { status: false }
  }
}
