// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { WebPlugin } from '@capacitor/core'
import type { AdMobPlusPlugin } from './definitions'

export class AdMobPlusWeb extends WebPlugin implements AdMobPlusPlugin {
  async start(
    ...opts: Parameters<AdMobPlusPlugin['start']>
  ): ReturnType<AdMobPlusPlugin['start']> {
    console.log('start', opts)
  }

  async configure(
    ...opts: Parameters<AdMobPlusPlugin['configure']>
  ): ReturnType<AdMobPlusPlugin['configure']> {
    console.log('configure', opts)
  }

  async configRequest(
    ...opts: Parameters<AdMobPlusPlugin['configRequest']>
  ): ReturnType<AdMobPlusPlugin['configRequest']> {
    console.log('configRequest', opts)
  }

  async bannerShow(
    ...opts: Parameters<AdMobPlusPlugin['bannerShow']>
  ): ReturnType<AdMobPlusPlugin['bannerShow']> {
    console.log('bannerShow', opts)
  }

  async bannerHide(
    ...opts: Parameters<AdMobPlusPlugin['bannerHide']>
  ): ReturnType<AdMobPlusPlugin['bannerHide']> {
    console.log('bannerHide', opts)
  }

  async interstitialLoad(
    ...opts: Parameters<AdMobPlusPlugin['interstitialLoad']>
  ): ReturnType<AdMobPlusPlugin['interstitialLoad']> {
    console.log('interstitialLoad', opts)
  }

  async interstitialShow(
    ...opts: Parameters<AdMobPlusPlugin['interstitialShow']>
  ): ReturnType<AdMobPlusPlugin['interstitialShow']> {
    console.log('interstitialShow', opts)
  }

  async rewardedLoad(
    ...opts: Parameters<AdMobPlusPlugin['rewardedLoad']>
  ): ReturnType<AdMobPlusPlugin['rewardedLoad']> {
    console.log('rewardedLoad', opts)
  }

  async rewardedShow(
    ...opts: Parameters<AdMobPlusPlugin['rewardedShow']>
  ): ReturnType<AdMobPlusPlugin['rewardedShow']> {
    console.log('rewardedShow', opts)
  }

  async rewardedInterstitialLoad(
    ...opts: Parameters<AdMobPlusPlugin['rewardedInterstitialLoad']>
  ): ReturnType<AdMobPlusPlugin['rewardedInterstitialLoad']> {
    console.log('rewardedInterstitialLoad', opts)
  }

  async rewardedInterstitialShow(
    ...opts: Parameters<AdMobPlusPlugin['rewardedInterstitialShow']>
  ): ReturnType<AdMobPlusPlugin['rewardedInterstitialShow']> {
    console.log('rewardedInterstitialShow', opts)
  }

  async trackingAuthorizationStatus(
    ...opts: Parameters<AdMobPlusPlugin['trackingAuthorizationStatus']>
  ): ReturnType<AdMobPlusPlugin['trackingAuthorizationStatus']> {
    console.log('trackingAuthorizationStatus', opts)
    return { status: false }
  }

  async requestTrackingAuthorization(
    ...opts: Parameters<AdMobPlusPlugin['requestTrackingAuthorization']>
  ): ReturnType<AdMobPlusPlugin['requestTrackingAuthorization']> {
    console.log('requestTrackingAuthorization', opts)
    return { status: false }
  }
}
