// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
struct AMSEvents {
    static let interstitial_close = "admob.interstitial.close"
    static let interstitial_exit_app = "admob.interstitial.exit_app"
    static let interstitial_load = "admob.interstitial.load"
    static let interstitial_load_fail = "admob.interstitial.load_fail"
    static let interstitial_open = "admob.interstitial.open"
    static let ready = "admob.ready"
    static let reward_video_close = "admob.reward_video.close"
    static let reward_video_complete = "admob.reward_video.complete"
    static let reward_video_exit_app = "admob.reward_video.exit_app"
    static let reward_video_load = "admob.reward_video.load"
    static let reward_video_load_fail = "admob.reward_video.load_fail"
    static let reward_video_open = "admob.reward_video.open"
    static let reward_video_reward = "admob.reward_video.reward"
    static let reward_video_start = "admob.reward_video.start"
}
