// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
package admob.plugin;

import com.google.android.gms.ads.AdSize;

public enum AdSizeType {
    BANNER, LARGE_BANNER, MEDIUM_RECTANGLE, FULL_BANNER, LEADERBOARD, SMART_BANNER;

    public static AdSize getAdSize(Object adSize) {
      if (AdSizeType.BANNER.equals(adSize)) {
          return AdSize.BANNER;
      }
      if (AdSizeType.LARGE_BANNER.equals(adSize)) {
          return AdSize.LARGE_BANNER;
      }
      if (AdSizeType.MEDIUM_RECTANGLE.equals(adSize)) {
          return AdSize.MEDIUM_RECTANGLE;
      }
      if (AdSizeType.FULL_BANNER.equals(adSize)) {
          return AdSize.FULL_BANNER;
      }
      if (AdSizeType.LEADERBOARD.equals(adSize)) {
          return AdSize.LEADERBOARD;
      }
      if (AdSizeType.SMART_BANNER.equals(adSize)) {
          return AdSize.SMART_BANNER;
      }
      return null;
    }
}
