// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
enum AMBEvents: String, CaseIterable {
    case adClick = "ad.click"
    case adDismiss = "ad.dismiss"
    case adImpression = "ad.impression"
    case adLoad = "ad.load"
    case adLoadFail = "ad.loadfail"
    case adShow = "ad.show"
    case adShowFail = "ad.showfail"
}
