// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
struct AMBBannerPosition {
    static let bottom = "bottom"
    static let top = "top"
}

struct AMBEvents {
    static let bannerClick = "admob.banner.click"
    static let bannerClose = "admob.banner.close"
    static let bannerImpression = "admob.banner.impression"
    static let bannerLoad = "admob.banner.load"
    static let bannerLoadFail = "admob.banner.loadFail"
    static let bannerOpen = "admob.banner.open"
    static let interstitialDismiss = "admob.interstitial.dismiss"
    static let interstitialLoad = "admob.interstitial.load"
    static let interstitialLoadFail = "admob.interstitial.loadFail"
    static let interstitialShow = "admob.interstitial.show"
    static let interstitialShowFail = "admob.interstitial.showFail"
    static let ready = "admob.ready"
    static let rewardedDismiss = "admob.rewarded.dismiss"
    static let rewardedLoad = "admob.rewarded.load"
    static let rewardedLoadFail = "admob.rewarded.loadFail"
    static let rewardedReward = "admob.rewarded.reward"
    static let rewardedShow = "admob.rewarded.show"
    static let rewardedShowFail = "admob.rewarded.showFail"
}
