// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
struct AMSBannerPosition {
    static let bottom = "bottom"
    static let top = "top"
}

struct AMSEvents {
    static let bannerClick = "admob.banner.click"
    static let bannerClose = "admob.banner.close"
    static let bannerExitApp = "admob.banner.exit_app"
    static let bannerImpression = "admob.banner.impression"
    static let bannerLoad = "admob.banner.load"
    static let bannerLoadFail = "admob.banner.load_fail"
    static let bannerOpen = "admob.banner.open"
    static let interstitialClick = "admob.interstitial.click"
    static let interstitialClose = "admob.interstitial.close"
    static let interstitialExitApp = "admob.interstitial.exit_app"
    static let interstitialImpression = "admob.interstitial.impression"
    static let interstitialLoad = "admob.interstitial.load"
    static let interstitialLoadFail = "admob.interstitial.load_fail"
    static let interstitialOpen = "admob.interstitial.open"
    static let ready = "admob.ready"
    static let rewardVideoClick = "admob.reward_video.click"
    static let rewardVideoClose = "admob.reward_video.close"
    static let rewardVideoComplete = "admob.reward_video.complete"
    static let rewardVideoExitApp = "admob.reward_video.exit_app"
    static let rewardVideoImpression = "admob.reward_video.impression"
    static let rewardVideoLoad = "admob.reward_video.load"
    static let rewardVideoLoadFail = "admob.reward_video.load_fail"
    static let rewardVideoOpen = "admob.reward_video.open"
    static let rewardVideoReward = "admob.reward_video.reward"
    static let rewardVideoStart = "admob.reward_video.start"
}
