// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
struct AMSBannerPosition {
    static let bottom = "bottom"
    static let top = "top"
}

struct AMSEvents {
    static let bannerClick = "admob.banner.click"
    static let bannerClose = "admob.banner.close"
    static let bannerImpression = "admob.banner.impression"
    static let bannerLoad = "admob.banner.load"
    static let bannerLoadFail = "admob.banner.loadFail"
    static let bannerOpen = "admob.banner.open"
    static let initComplete = "admob.initComplete"
    static let interstitialClick = "admob.interstitial.click"
    static let interstitialClose = "admob.interstitial.close"
    static let interstitialImpression = "admob.interstitial.impression"
    static let interstitialLoad = "admob.interstitial.load"
    static let interstitialLoadFail = "admob.interstitial.loadFail"
    static let interstitialOpen = "admob.interstitial.open"
    static let ready = "admob.ready"
    static let rewardedClick = "admob.rewarded.click"
    static let rewardedClose = "admob.rewarded.close"
    static let rewardedComplete = "admob.rewarded.complete"
    static let rewardedImpression = "admob.rewarded.impression"
    static let rewardedLoad = "admob.rewarded.load"
    static let rewardedLoadFail = "admob.rewarded.loadFail"
    static let rewardedOpen = "admob.rewarded.open"
    static let rewardedReward = "admob.rewarded.reward"
    static let rewardedStart = "admob.rewarded.start"
}
