module.exports = {
  docs: [
    'index',
    {
      Capacitor: [
        'capacitor/installation',
        {
          'Ad Formats': [
            'capacitor/ads/banner',
            'capacitor/ads/interstitial',
            'capacitor/ads/rewarded',
            'capacitor/ads/rewarded-interstitial',
          ],
          API: [
            {
              type: 'autogenerated',
              dirName: 'capacitor/api',
            },
          ],
        },
        {
          type: 'link',
          label: 'CHANGELOG',
          href: 'https://github.com/admob-plus/admob-plus/blob/master/packages/capacitor/CHANGELOG.md',
        },
      ],
      Cordova: [
        'cordova/getting-started',
        'cordova/installation',
        {
          'Ad Formats': [
            'cordova/ads/app-open',
            'cordova/ads/banner',
            'cordova/ads/interstitial',
            'cordova/ads/native',
            'cordova/ads/rewarded',
            'cordova/ads/rewarded-interstitial',
          ],
        },
        'cordova/test-ads',
        {
          'Advanced Topics': [
            'cordova/rewarded-ads-ssv',
            'cordova/targeting',
            'cordova/volume-control',
          ],
          'User Consent': [
            'cordova/consent/request',
            {
              API: [{ type: 'autogenerated', dirName: 'cordova/consent/api' }],
            },
          ],
          API: [{ type: 'autogenerated', dirName: 'cordova/api' }],
        },
        'cordova/faq',
        {
          type: 'link',
          label: 'CHANGELOG',
          href: 'https://github.com/admob-plus/admob-plus/blob/master/packages/cordova/CHANGELOG.md',
        },
      ],
      Ionic: [
        'ionic/getting-started',
        'ionic/installation',
        {
          'Ad Formats': [
            'ionic/ads/banner',
            'ionic/ads/interstitial',
            'ionic/ads/native',
            'ionic/ads/rewarded',
            'ionic/ads/rewarded-interstitial',
          ],
          API: [{ type: 'autogenerated', dirName: 'ionic/api' }],
        },
        {
          type: 'link',
          label: 'CHANGELOG',
          href: 'https://github.com/admob-plus/admob-plus/blob/master/packages/ionic/CHANGELOG.md',
        },
      ],
      'React Native': [
        'react-native/installation',
        {
          'Ad Formats': [
            'react-native/ads/interstitial',
            'react-native/ads/rewarded',
            'react-native/ads/rewarded-interstitial',
          ],
          API: [{ type: 'autogenerated', dirName: 'react-native/api' }],
        },
        {
          type: 'link',
          label: 'CHANGELOG',
          href: 'https://github.com/admob-plus/admob-plus/blob/master/packages/react-native/CHANGELOG.md',
        },
      ],
    },
    'troubleshooting',
  ],
}
