platform :ios, '12.0'
use_frameworks!

# workaround to avoid Xcode caching of Pods that requires
# Product -> Clean Build Folder after new Cordova plugins installed
# Requires CocoaPods 1.6 or newer
install! 'cocoapods', :disable_input_output_paths => true

def capacitor_pods
  pod 'Capacitor', :path => '../../../../.yarn/unplugged/@capacitor-ios-virtual-5336fc939c/node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../../../.yarn/unplugged/@capacitor-ios-virtual-5336fc939c/node_modules/@capacitor/ios'
  pod 'CapacitorApp', :path => '../../../../.yarn/unplugged/@capacitor-app-virtual-8d3af7f3a0/node_modules/@capacitor/app'
  pod 'CapacitorHaptics', :path => '../../../../.yarn/unplugged/@capacitor-haptics-virtual-2007ad061c/node_modules/@capacitor/haptics'
  pod 'CapacitorKeyboard', :path => '../../../../.yarn/unplugged/@capacitor-keyboard-virtual-825d2827bf/node_modules/@capacitor/keyboard'
  pod 'CapacitorStatusBar', :path => '../../../../.yarn/unplugged/@capacitor-status-bar-virtual-4ccdb7503f/node_modules/@capacitor/status-bar'
end

target 'App' do
  capacitor_pods
  # Add your Pods here
end
