// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
package admob.plus.cordova

object Actions {
    const val AD_CREATE = "adCreate"
    const val AD_HIDE = "adHide"
    const val AD_IS_LOADED = "adIsLoaded"
    const val AD_LOAD = "adLoad"
    const val AD_SHOW = "adShow"
    const val BANNER_CONFIG = "bannerConfig"
    const val CONFIGURE = "configure"
    const val READY = "ready"
    const val START = "start"
    const val WEBVIEW_GOTO = "webviewGoto"
}

object Events {
    const val AD_CLICK = "admob.ad.click"
    const val AD_DISMISS = "admob.ad.dismiss"
    const val AD_IMPRESSION = "admob.ad.impression"
    const val AD_LOAD = "admob.ad.load"
    const val AD_LOAD_FAIL = "admob.ad.loadfail"
    const val AD_REWARD = "admob.ad.reward"
    const val AD_SHOW = "admob.ad.show"
    const val AD_SHOW_FAIL = "admob.ad.showfail"
    const val BANNER_SIZE = "admob.banner.size"
    const val READY = "admob.ready"
}
