package admob.plus.cordova

object Actions {
    const val AD_CREATE = "adCreate"
    const val AD_HIDE = "adHide"
    const val AD_IS_LOADED = "adIsLoaded"
    const val AD_LOAD = "adLoad"
    const val AD_SHOW = "adShow"
    const val BANNER_CONFIG = "bannerConfig"
    const val BANNER_HIDE = "bannerHide"
    const val BANNER_LOAD = "bannerLoad"
    const val BANNER_SHOW = "bannerShow"
    const val CONFIGURE = "configure"
    const val CONFIG_REQUEST = "configRequest"
    const val INTERSTITIAL_IS_LOADED = "interstitialIsLoaded"
    const val INTERSTITIAL_LOAD = "interstitialLoad"
    const val INTERSTITIAL_SHOW = "interstitialShow"
    const val READY = "ready"
    const val REQUEST_TRACKING_AUTHORIZATION = "requestTrackingAuthorization"
    const val REWARDED_INTERSTITIAL_IS_LOADED = "rewardedInterstitialIsLoaded"
    const val REWARDED_INTERSTITIAL_LOAD = "rewardedInterstitialLoad"
    const val REWARDED_INTERSTITIAL_SHOW = "rewardedInterstitialShow"
    const val REWARDED_IS_LOADED = "rewardedIsLoaded"
    const val REWARDED_LOAD = "rewardedLoad"
    const val REWARDED_SHOW = "rewardedShow"
    const val SET_APP_MUTED = "setAppMuted"
    const val SET_APP_VOLUME = "setAppVolume"
    const val START = "start"
}

object Events {
    const val AD_CLICK = "admob.ad.click"
    const val AD_DISMISS = "admob.ad.dismiss"
    const val AD_IMPRESSION = "admob.ad.impression"
    const val AD_LOAD = "admob.ad.load"
    const val AD_LOAD_FAIL = "admob.ad.loadfail"
    const val AD_REWARD = "admob.ad.reward"
    const val AD_SHOW = "admob.ad.show"
    const val AD_SHOW_FAIL = "admob.ad.showfail"
    const val BANNER_CLICK = "admob.banner.click"
    const val BANNER_CLOSE = "admob.banner.close"
    const val BANNER_IMPRESSION = "admob.banner.impression"
    const val BANNER_LOAD = "admob.banner.load"
    const val BANNER_LOAD_FAIL = "admob.banner.loadfail"
    const val BANNER_OPEN = "admob.banner.open"
    const val BANNER_SIZE = "admob.banner.size"
    const val BANNER_SIZE_CHANGE = "admob.banner.sizechange"
    const val INTERSTITIAL_DISMISS = "admob.interstitial.dismiss"
    const val INTERSTITIAL_IMPRESSION = "admob.interstitial.impression"
    const val INTERSTITIAL_LOAD = "admob.interstitial.load"
    const val INTERSTITIAL_LOAD_FAIL = "admob.interstitial.loadfail"
    const val INTERSTITIAL_SHOW = "admob.interstitial.show"
    const val INTERSTITIAL_SHOW_FAIL = "admob.interstitial.showfail"
    const val READY = "admob.ready"
    const val REWARDED_DISMISS = "admob.rewarded.dismiss"
    const val REWARDED_IMPRESSION = "admob.rewarded.impression"
    const val REWARDED_INTERSTITIAL_DISMISS = "admob.rewardedi.dismiss"
    const val REWARDED_INTERSTITIAL_IMPRESSION = "admob.rewardedi.impression"
    const val REWARDED_INTERSTITIAL_LOAD = "admob.rewardedi.load"
    const val REWARDED_INTERSTITIAL_LOAD_FAIL = "admob.rewardedi.loadfail"
    const val REWARDED_INTERSTITIAL_REWARD = "admob.rewardedi.reward"
    const val REWARDED_INTERSTITIAL_SHOW = "admob.rewardedi.show"
    const val REWARDED_INTERSTITIAL_SHOW_FAIL = "admob.rewardedi.showfail"
    const val REWARDED_LOAD = "admob.rewarded.load"
    const val REWARDED_LOAD_FAIL = "admob.rewarded.loadfail"
    const val REWARDED_REWARD = "admob.rewarded.reward"
    const val REWARDED_SHOW = "admob.rewarded.show"
    const val REWARDED_SHOW_FAIL = "admob.rewarded.showfail"
}
